export const USER_REGISTER_LOADING = 'USER_REGISTER_LOADING'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'

export const USER_LOADING = 'USER_LOADING'
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS'
export const USER_LOAD_FAILED= 'USER_LOAD_FAILED'

export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_RESET_ERRORS = 'USER_RESET_ERRORS'

export const USER_FIELDS_UPDATE_LOADING = 'USER_FIELDS_UPDATE_LOADING'
export const USER_FIELDS_UPDATE_SUCCESS = 'USER_FIELDS_UPDATE_SUCCESS'
export const USER_FIELDS_UPDATE_FAILED = 'USER_FIELDS_UPDATE_FAILED'

export const USER_RESET_PASSWORD_LOADING = 'USER_RESET_PASSWORD_LOADING'
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS'
export const USER_RESET_PASSWORD_FAILED = 'USER_RESET_PASSWORD_FAILED'

export const USER_CHANGE_PASSWORD_LOADING = 'USER_CHANGE_PASSWORD_LOADING'
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS'
export const USER_CHANGE_PASSWORD_FAILED = 'USER_CHANGE_PASSWORD_FAILED'

export const USER_SET_NEW_PASSWORD_LOADING = 'USER_SET_NEW_PASSWORD_LOADING'
export const USER_SET_NEW_PASSWORD_SUCCESS = 'USER_SET_NEW_PASSWORD_SUCCESS'
export const USER_SET_NEW_PASSWORD_FAILED = 'USER_SET_NEW_PASSWORD_FAILED'

export const USER_CHANGE_EMAIL_LOADING = 'USER_CHANGE_EMAIL_LOADING'
export const USER_CHANGE_EMAIL_SUCCESS = 'USER_CHANGE_EMAIL_SUCCESS'
export const USER_CHANGE_EMAIL_FAILED = 'USER_CHANGE_EMAIL_FAILED'

export const USER_ACCOUNT_DELETE_LOADING = 'USER_ACCOUNT_DELETE_LOADING'
export const USER_ACCOUNT_DELETE_SUCCESS = 'USER_ACCOUNT_DELETE_SUCCESS'
export const USER_ACCOUNT_DELETE_FAILED = 'USER_ACCOUNT_DELETE_FAILED'

export const USER_DELETE_ACCOUNT_LOADING = 'USER_DELETE_ACCOUNT_LOADING'
export const USER_DELETE_ACCOUNT_SUCCESS = 'USER_DELETE_ACCOUNT_SUCCESS'
export const USER_DELETE_ACCOUNT_FAILED = 'USER_DELETE_ACCOUNT_FAILED'

export const AUTH_GOOGLE_OAUTH_URL_LOADING = 'AUTH_GOOGLE_OAUTH_URL_LOADING'
export const AUTH_GOOGLE_OAUTH_URL_LOAD_SUCCESS = 'AUTH_GOOGLE_OAUTH_URL_LOAD_SUCCESS'
export const AUTH_GOOGLE_OAUTH_URL_LOAD_FAILED = 'AUTH_GOOGLE_OAUTH_URL_LOAD_FAILED'

export const AUTH_RESEND_VERIFICATION_EMAIL_LOADING = 'AUTH_RESEND_VERIFICATION_EMAIL_LOADING'
export const AUTH_RESEND_VERIFICATION_EMAIL_SUCCESS = 'AUTH_RESEND_VERIFICATION_EMAIL_SUCCESS'
export const AUTH_RESEND_VERIFICATION_EMAIL_FAILED = 'AUTH_RESEND_VERIFICATION_EMAIL_FAILED'

export const AUTH_REQUEST_RESET_PASSWORD_LOADING = 'AUTH_REQUEST_RESET_PASSWORD_LOADING'
export const AUTH_REQUEST_RESET_PASSWORD_SUCCESS = 'AUTH_REQUEST_RESET_PASSWORD_SUCCESS'
export const AUTH_REQUEST_RESET_PASSWORD_FAILED = 'AUTH_REQUEST_RESET_PASSWORD_FAILED'

export const AUTH_VERIFY_EMAIL_LOADING = 'AUTH_VERIFY_EMAIL_LOADING'
export const AUTH_VERIFY_EMAIL_SUCCESS = 'AUTH_VERIFY_EMAIL_SUCCESS'
export const AUTH_VERIFY_EMAIL_FAILED = 'AUTH_VERIFY_EMAIL_FAILED'

export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS'
export const PROFILE_LOAD_FAILED = 'PROFILE_LOAD_FAILED'

export const PROFILE_FIELDS_UPDATE_LOADING = 'PROFILE_FIELDS_UPDATE_LOADING'
export const PROFILE_FIELDS_UPDATE_SUCCESS = 'PROFILE_FIELDS_UPDATE_SUCCESS'
export const PROFILE_FIELDS_UPDATE_FAILED = 'PROFILE_FIELDS_UPDATE_FAILED'

export const PROFILE_AVATAR_UPDATE_LOADING = 'PROFILE_AVATAR_UPDATE_LOADING'
export const PROFILE_AVATAR_UPDATE_SUCCESS = 'PROFILE_AVATAR_UPDATE_SUCCESS'
export const PROFILE_AVATAR_UPDATE_FAILED = 'PROFILE_AVATAR_UPDATE_FAILED'

export const PROFILE_NEWSLETTER_UPDATE_LOADING = 'PROFILE_NEWSLETTER_UPDATE_LOADING'
export const PROFILE_NEWSLETTER_UPDATE_SUCCESS = 'PROFILE_NEWSLETTER_UPDATE_SUCCESS'
export const PROFILE_NEWSLETTER_UPDATE_FAILED = 'PROFILE_NEWSLETTER_UPDATE_FAILED'

export const PROFILE_PRIVATE_ACCOUNT_UPDATE_LOADING = 'PROFILE_PRIVATE_ACCOUNT_UPDATE_LOADING'
export const PROFILE_PRIVATE_ACCOUNT_UPDATE_SUCCESS = 'PROFILE_PRIVATE_ACCOUNT_UPDATE_SUCCESS'
export const PROFILE_PRIVATE_ACCOUNT_UPDATE_FAILED = 'PROFILE_PRIVATE_ACCOUNT_UPDATE_FAILED'

export const PUBLIC_PROFILE_LOADING = 'PUBLIC_PROFILE_LOADING'
export const PUBLIC_PROFILE_LOAD_SUCCESS = 'PUBLIC_PROFILE_LOAD_SUCCESS'
export const PUBLIC_PROFILE_LOAD_FAILED = 'PUBLIC_PROFILE_LOAD_FAILED'

export const PROFILE_AVATAR_DELETE_LOADING = "PROFILE_AVATAR_DELETE_LOADING"
export const PROFILE_AVATAR_DELETE_SUCCESS = "PROFILE_AVATAR_DELETE_SUCCCESS"
export const PROFILE_AVATAR_DELETE_FAILED = "PROFILE_AVATAR_DELETE_FAILED"

export const BOOK_ADD_TO_WISHLIST_LOADING = 'BOOK_ADD_TO_WISHLIST_LOADING'
export const BOOK_ADD_TO_WISHLIST_SUCCESS = 'BOOK_ADD_TO_WISHLIST_SUCCESS'
export const BOOK_ADD_TO_WISHLIST_FAILED = 'BOOK_ADD_TO_WISHLIST_FAILED'

export const BOOK_REMOVE_FROM_WISHLIST_LOADING = 'BOOK_REMOVE_FROM_WISHLIST_LOADING'
export const BOOK_REMOVE_FROM_WISHLIST_SUCCESS = 'BOOK_REMOVE_FROM_WISHLIST_SUCCESS'
export const BOOK_REMOVE_FROM_WISHLIST_FAILED = 'BOOK_REMOVE_FROM_WISHLIST_FAILED'

export const BOOK_ADD_TO_MY_BOOKS_LOADING = 'BOOK_ADD_TO_MY_BOOKS_LOADING'
export const BOOK_ADD_TO_MY_BOOKS_SUCCESS = 'BOOK_ADD_TO_MY_BOOKS_SUCCESS'
export const BOOK_ADD_TO_MY_BOOKS_FAILED = 'BOOK_ADD_TO_MY_BOOKS_FAILED'

export const BOOK_REMOVE_FROM_MY_BOOKS_LOADING = 'BOOK_REMOVE_FROM_MY_BOOKS_LOADING'
export const BOOK_REMOVE_FROM_MY_BOOKS_SUCCESS = 'BOOK_REMOVE_FROM_MY_BOOKS_SUCCESS'
export const BOOK_REMOVE_FROM_MY_BOOKS_FAILED = 'BOOK_REMOVE_FROM_MY_BOOKS_FAILED'

export const BOOK_ADD_TO_RECENTLY_VIEWED_BOOKS_LOADING = 'BOOK_ADD_TO_RECENTLY_VIEWED_BOOKS_LOADING'
export const BOOK_ADD_TO_RECENTLY_VIEWED_BOOKS_SUCCESS = 'BOOK_ADD_TO_RECENTLY_VIEWED_BOOKS_SUCCESS'
export const BOOK_ADD_TO_RECENTLY_VIEWED_BOOKS_FAILED = 'BOOK_ADD_TO_RECENTLY_VIEWED_BOOKS_FAILED'

export const BOOK_GLOABAL_SEARCH_LOADING = 'BOOK_GLOABAL_SEARCH_LOADING'
export const BOOK_GLOABAL_SEARCH_SUCCESS = 'BOOK_GLOABAL_SEARCH_SUCCESS'
export const BOOK_GLOABAL_SEARCH_FAILED = 'BOOK_GLOABAL_SEARCH_FAILED'

export const BOOK_CURRENT_BOOK_LOADING = 'BOOK_CURRENT_BOOK_LOADING'
export const BOOK_CURRENT_BOOK_LOAD_SUCCESS = 'BOOK_CURRENT_BOOK_LOAD_SUCCESS'
export const BOOK_CURRENT_BOOK_LOAD_FAILED = 'BOOK_CURRENT_BOOK_LOAD_FAILED'

export const BOOK_GET_BEST_SELLER_BOOKS_LOADING = 'BOOK_GET_BEST_SELLER_BOOKS_LOADING'
export const BOOK_GET_BEST_SELLER_BOOKS_SUCCESS = 'BOOK_GET_BEST_SELLER_BOOKS_SUCCESS'
export const BOOK_GET_BEST_SELLER_BOOKS_FAILED = 'BOOK_GET_BEST_SELLER_BOOKS_FAILED'

export const REVIEW_ADD_REVIEW_LOADING = 'REVIEW_ADD_REVIEW_LOADING'
export const REVIEW_ADD_REVIEW_SUCCESS = 'REVIEW_ADD_REVIEW_SUCCESS'
export const REVIEW_ADD_REVIEW_FAILED = 'REVIEW_ADD_REVIEW_FAILED'

export const REVIEW_REMOVE_REVIEW_LOADING = 'REVIEW_REMOVE_REVIEW_LOADING'
export const REVIEW_REMOVE_REVIEW_SUCCESS = 'REVIEW_REMOVE_REVIEW_SUCCESS'
export const REVIEW_REMOVE_REVIEW_FAILED = 'REVIEW_REMOVE_REVIEW_FAILED'

export const REVIEW_SORT_MY_REVIEWS_BY_DATE_NEWEST = 'REVIEW_SORT_MY_REVIEWS_BY_DATE_NEWEST'
export const REVIEW_SORT_MY_REVIEWS_BY_DATE_OLDEST = 'REVIEW_SORT_MY_REVIEWS_BY_DATE_OLDEST'
export const REVIEW_SORT_MY_REVIEWS_ALPHABETICALLY = 'REVIEW_SORT_MY_REVIEWS_ALPHABETICALLY'
export const REVIEW_SORT_MY_REVIEWS_BY_RATING_HIGHEST = 'REVIEW_SORT_MY_REVIEWS_BY_RATING_HIGHEST'
export const REVIEW_SORT_MY_REVIEWS_BY_RATING_LOWEST = 'REVIEW_SORT_MY_REVIEWS_BY_RATING_LOWEST'




// ERRORS
export const RESET_ALL_ALERTS = 'RESET_ALL_ALERTS'

